### ISSUE TITLE
Can't parse text version of individuals table with blank columns

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1824]
The example from the [data-model api docs](https://github.com/tskit-dev/tskit/blob/main/docs/data-model.rst#individual-text-format) can't be read in, either in strict mode:

```python
import io
import tskit

individuals = """\
flags\tlocation\tparents
0\t0.5,1.2\t-1,-1
0\t1.0,3.4\t0,-1
0\t1.2\t
"""

tskit.parse_individuals(io.StringIO(individuals))
```

which gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yan/Documents/Research/BDI/tskit/python/tskit/trees.py", line 2928, in parse_individuals
    parents = tuple(map(int, parents_string.split(",")))
ValueError: invalid literal for int() with base 10: '\n'
``` 

Or not in strict mode

```python
individuals = """\
flags       location     parents
0           0.5,1.2      -1,-1
0           1.0,3.4      0,-1
0           1.2  
"""

tskit.parse_individuals(io.StringIO(individuals), strict=False)
```

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yan/Documents/Research/BDI/tskit/python/tskit/trees.py", line 2926, in parse_individuals
    parents_string = tokens[parents_index]
IndexError: list index out of range
```

**Comment by hyanwong** [comment]
I guess in the test suite we should try round-tripping an individuals table (or some other equivalent table) with blank columns.

**Comment by hyanwong** [comment]
OK, the strict=True case is fixed by properly stripping newlines (https://github.com/tskit-dev/tskit/commit/7f62573980fe7cdb6d3e614893b0266f1a40d17e). I don't think we can do anything about the `strict=False` case, because the spaces are all separators, so we just need to say "if you have missing data in columns, you have to use strict=True.

So closing.
