### ISSUE TITLE
MISSING_DATA error?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#289]
Hey @jeromekelleher, I'm trying to run some tests in `test_topology.py`, but I'm getting this error:
I'm not sure exactly what I've done, but it looks as if I get this problem even when I backtrack through my commits to a point where I'm on the master branch.
Do you know what might be causing this?
```
======================================================================
ERROR: Failure: AttributeError (module '_tskit' has no attribute 'MISSING_DATA')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/miniconda3/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/miniconda3/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/miniconda3/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/miniconda3/lib/python3.7/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/miniconda3/lib/python3.7/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gtsambos/Projects/tskit/python/tests/__init__.py", line 27, in <module>
    from .simplify import *  # NOQA
  File "/Users/gtsambos/Projects/tskit/python/tests/simplify.py", line 30, in <module>
    import tskit
  File "/Users/gtsambos/Projects/tskit/python/tskit/__init__.py", line 25, in <module>
    MISSING_DATA = _tskit.MISSING_DATA
AttributeError: module '_tskit' has no attribute 'MISSING_DATA'

----------------------------------------------------------------------
```

**Comment by gtsambos** [comment]
FYI, things I've tried already are - upgrading msprime, rebasing my fork of tskit.

**Comment by jeromekelleher** [comment]
You need to rebuild the low-level module: run ``make`` in the python directory.

**Comment by gtsambos** [comment]
Ah yes, I keep on forgetting this 🤦‍♂
