### ISSUE TITLE
`genetic_relatedness` thinks it needs 2 samples sets but is valid with only one

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#3055]
Self-comparisons are valid for this statistic, and so this should work:
```
>> ts.genetic_relatedness([[0]], indexes=[(0,0)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/projects/tskit-dev/tsvenv/lib/python3.12/site-packages/tskit/trees.py", line 8403, in genetic_relatedness
    out = self.__k_way_sample_set_stat(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/projects/tskit-dev/tsvenv/lib/python3.12/site-packages/tskit/trees.py", line 7843, in __k_way_sample_set_stat
    stat = self.__run_windowed_stat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/projects/tskit-dev/tsvenv/lib/python3.12/site-packages/tskit/trees.py", line 7664, in __run_windowed_stat
    stat = method(*args, **kwargs, windows=windows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tskit.LibraryError: Insufficient sample sets provided. (TSK_ERR_INSUFFICIENT_SAMPLE_SETS)
```

**Comment by andrewkern** [comment]
I've tried to fix this over in #3235
