### ISSUE TITLE
Appveyor builds broken

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#344]
```
SSL_CERT_FILE: <not set>
282
283cd python
284python setup.py build_ext --inplace
285running build_ext
286Traceback (most recent call last):
287  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
288    from . import multiarray
289  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
290    from . import overrides
291  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
292    from numpy.core._multiarray_umath import (
293ImportError: DLL load failed: The specified module could not be found.
294
295During handling of the above exception, another exception occurred:
296
297Traceback (most recent call last):
298  File "setup.py", line 107, in <module>
299    platforms=["POSIX", "Windows", "MacOS X"],
300  File "C:\Miniconda36-x64\lib\site-packages\setuptools\__init__.py", line 145, in setup
301    return distutils.core.setup(**attrs)
302  File "C:\Miniconda36-x64\lib\distutils\core.py", line 148, in setup
303    dist.run_commands()
304  File "C:\Miniconda36-x64\lib\distutils\dist.py", line 966, in run_commands
305    self.run_command(cmd)
306  File "C:\Miniconda36-x64\lib\distutils\dist.py", line 984, in run_command
307    cmd_obj.ensure_finalized()
308  File "C:\Miniconda36-x64\lib\distutils\cmd.py", line 107, in ensure_finalized
309    self.finalize_options()
310  File "setup.py", line 19, in finalize_options
311    import numpy
312  File "C:\Miniconda36-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
313    from . import core
314  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
315    raise ImportError(msg)
316ImportError: 
317
318IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
319
320Importing the numpy c-extensions failed.
321- Try uninstalling and reinstalling numpy.
322- If you have already done that, then:
323  1. Check that you expected to use Python3.7 from "C:\Miniconda36-x64\python.exe",
324     and that you have no directories in your PATH or PYTHONPATH that can
325     interfere with the Python and numpy version "1.17.1" you're trying to use.
326  2. If (1) looks fine, you can open a new issue at
327     https://github.com/numpy/numpy/issues.  Please include details on:
328     - how you installed Python
329     - how you installed numpy
330     - your operating system
331     - whether or not you have multiple versions of Python installed
332     - if you built from source, your compiler versions and ideally a build log
333
334- If you're working with a numpy git repository, try `git clean -xdf`
335  (removes all files not under version control) and rebuild numpy.
336
337Note: this error has many possible causes, so please don't comment on
338an existing issue about this - open a new one instead.
339
340Original error was: DLL load failed: The specified module could not be found.
341
342
```

Possibly something to do with upstream changes in pinned numpy version in conda-forge?

**Comment by jeromekelleher** [comment]
Possibly the issue here is with different numpy pinning on msprime and tskit. Running a rebuild on msprime-feedstock to rule this out: https://github.com/conda-forge/msprime-feedstock/pull/37

**Comment by jeromekelleher** [comment]
Looks like it might be this issue: https://github.com/ContinuumIO/anaconda-issues/issues/10628

**Comment by hyanwong** [comment]
I'm getting this on my tsinfer builds now: https://ci.appveyor.com/project/tskit-dev/tsinfer/builds/27093177 - how did you fix it?

**Comment by hyanwong** [comment]
@jeromekelleher - sorry - didn't see the link to your fix in https://github.com/tskit-dev/tskit/pull/345. I'll try implementing that for the tsinfer framework
