### ISSUE TITLE
tables.edges.squash() requires nodes to be in order of time

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#808]
Although tree sequences don't require nodes to be in time order, it seems like `squash()` requires them to be so. I think this probably counts as a bug (and there's probably an easy fix). Here's an example using tsinfer, which (if run with `simpify=False`), doesn't return nodes in time order:

```
>>> import tsinfer
>>> ts_old = msprime.simulate(10, recombination_rate=0, mutation_rate=5, random_seed=1)
>>> sd = tsinfer.SampleData.from_tree_sequence(ts_old, use_times=False)
>>> ts = tsinfer.infer(sd, simplify=False)
>>> tables = ts.dump_tables()  # Valid tables, but nodes not ordered
>>> print(tables.tree_sequence())  # Works
<tskit.trees.TreeSequence object at 0x7fc9c68be4f0>
>>> tables.edges.squash()
>>> print(tables.tree_sequence())  # Fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tskit/tables.py", line 2198, in tree_sequence
    return tskit.TreeSequence.load_tables(self)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tskit/trees.py", line 2924, in load_tables
    ts.load_tables(tables.ll_tables)
_tskit.LibraryError: Edges must be listed in (time[parent], child, left) order; time[parent] order violated

```

**Comment by hyanwong** [comment]
I think we should also allow `tables.edges` to initially be in any order. I guess all we need to do is to call `tables.sort()` beforehand, and this will work. In fact, from some testing, it looks like if we call `tables.sort()` *after* `squash()` too, we don't hit the bug above. Is this the best approach to fixing this, @gtsambos, or is there a simpler fix when ordering the returned edges (e.g. using node_time for the ordering, rather than node_id?)

**Comment by jeromekelleher** [comment]
So if we call ``squash`` here it doesn't raise an error and results in a malformed tree sequence? I'm not sure about calling ``sort`` beforehand (this is a very expensive operation) but we should definitely run a ``tsk_table_collection_check_integrity`` beforehand with whatever flags we need.

**Comment by hyanwong** [comment]
> So if we call `squash` here it doesn't raise an error and results in a malformed tree sequence? 

Yes (or rather, it results in tables which cannot be converted to a ts)

> I'm not sure about calling `sort` beforehand (this is a very expensive operation) but we should definitely run a `tsk_table_collection_check_integrity` beforehand with whatever flags we need.

If we require edge tables to be sorted before input to `squash`, we should specify this in the docs, I guess.

It still doesn't help the *output* requirements. I think this just needs some recoding, TBH - there's probably an assumption built-in that nodes are sorted in time order, or perhaps that the first `n` nodes are the `n` sample nodes. @gtsambos will probably know.

**Comment by benjeffery** [comment]
We've currently got this down as Python 0.3.1 - but isn't this a C issue? If not then `C_0.99.6` is ready to go.

**Comment by jeromekelleher** [comment]
Right, so I don't think is a bug, but rather a documentation issue. The problem is that this is a method of the **edge table** and therefore knows nothing about the times of parents. In order to get things into the order that it need so we can see edges that need squashing, this function does a sort by parent ID, child ID then left coordinate. Squashable edges are then always adjacent. For the output edges to be valid for a tree sequence, the parent IDs must then be in time order.

For us to change this behaviour we'd need to make a new method ``TableCollection.squash_edges`` which would be guaranteed to produce valid output. I think we just need a add a note to the docs, since this is a fairly niche operation, but I'm happy for us to create the new method if anyone really wants it.

I've dropped this into Python 0.3.2 @benjeffery

**Comment by hyanwong** [comment]
Shouldn't `squash` sort by time of parent first, then parent ID? That would still ensure that edges were adjacent. And if you are just sorting by parent ID, then won't you risk doing a lot of re-sorting that may not actually be required?

**Comment by hyanwong** [comment]
p.s. does `simplify()` squash edges too (in which case this isn't so important, I suppose)? It wasn't clear to me from the `simplify()` documentation, but perhaps I missed it? If so, then perhaps that should be mentioned in the docs for `squash()` too?

**Comment by benjeffery** [comment]
> Shouldn't `squash` sort by time of parent first

As @jeromekelleher said, this method doesn't have access to the nodes, and therefore doesn't know the times.

**Comment by hyanwong** [comment]
> > Shouldn't `squash` sort by time of parent first
> 
> As @jeromekelleher said, this method doesn't have access to the nodes, and therefore doesn't know the times.

Oh, yes, of course.

Perhaps `squash()` should have an optional argument to give the order used for parents. By default this could be np.arange(ts.num_nodes), but the user could also give tables.nodes.time instead. Then `TableCollection.squash` would simply be implemented as `self.edges.squash(node_order=self.nodes.time)`? And it would allow people just using `squash()` to specify an order that didn't require much rearrangement.

**Comment by jeromekelleher** [comment]
I'm going change change this from a "bug" to a "documentation" issue.

**Comment by hyanwong** [comment]
I think this is already documented, but perhaps it could be clearer. At the end of the docstring it says:

> The new edge table will be sorted in the order (P, C, L, R): if the node table is ordered by increasing node time, as is common, this order will meet the [Edge requirements](https://tskit.dev/tskit/docs/latest/data-model.html#sec-edge-requirements) for a valid tree sequence, otherwise you will need to call [sort()](https://tskit.dev/tskit/docs/latest/python-api.html#tskit.TableCollection.sort) on the entire [TableCollection](https://tskit.dev/tskit/docs/latest/python-api.html#tskit.TableCollection).
