### ISSUE TITLE
h5py/conda-forge issue on Appveyor

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#87]
Building is failing on py36 on Windows/Appveyor because of a link time issue with [h5py]( ci.appveyor.com/project/tskit-dev/msprime/builds/21496431/job/9te7nd9iq5dua31j#L555). Disabling build for now.

**Comment by jeromekelleher** [comment]
This seems to have sorted itself out on msprime. Py36 should work fine.

**Comment by jeromekelleher** [comment]
Looks like this has moved to py37 now:
```
======================================================================
337ERROR: Failure: ImportError (DLL load failed: The specified module could not be found.)
338----------------------------------------------------------------------
339Traceback (most recent call last):
340  File "C:\Miniconda37-x64\lib\site-packages\nose\failure.py", line 39, in runTest
341    raise self.exc_val.with_traceback(self.tb)
342  File "C:\Miniconda37-x64\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
343    addr.filename, addr.module)
344  File "C:\Miniconda37-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
345    return self.importFromDir(dir_path, fqname)
346  File "C:\Miniconda37-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
347    mod = load_module(part_fqname, fh, filename, desc)
348  File "C:\Miniconda37-x64\lib\imp.py", line 244, in load_module
349    return load_package(name, filename)
350  File "C:\Miniconda37-x64\lib\imp.py", line 216, in load_package
351    return _load(spec)
352  File "<frozen importlib._bootstrap>", line 696, in _load
353  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
354  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
355  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
356  File "C:\projects\tskit\python\tskit\__init__.py", line 32, in <module>
357    from tskit.formats import *  # NOQA
358  File "C:\projects\tskit\python\tskit\formats.py", line 34, in <module>
359    import h5py
360  File "C:\Miniconda37-x64\lib\site-packages\h5py\__init__.py", line 26, in <module>
361    from . import _errors
362ImportError: DLL load failed: The specified module could not be found.
363
364
```

**Comment by jeromekelleher** [comment]
This problem is also happening in the msprime Appveyor builds. When it's resolved, update the CI there also.
