### ISSUE TITLE
Adding metadata schemas means tree sequences no longer pickle able

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#994]
Setting e.g. `tskit.MetadataSchema({"codec":"json"})` as the top level metadata schema means the tree seq is no longer pickleable. This means I can't e.g. pass the TS as a param to a multiprocessing subprocess.

```
import msprime
import pickle
ts = msprime.simulate(10)
a = pickle.dumps(ts)
tables = ts.dump_tables()
tables.metadata_schema = tskit.MetadataSchema({"codec":"json"})
a = pickle.dumps(tables.tree_sequence())
```

**Comment by jeromekelleher** [comment]
Good catch, thanks @hyanwong

**Comment by benjeffery** [comment]
Looks like we need better testing around pickling edge-cases. Will check other things are getting through ok.

**Comment by benjeffery** [comment]
So this nothing to do with pickling.
```python
>>> import tskit
>>> tc = tskit.TableCollection()
>>> tc.metadata
b''
>>> tc.metadata_schema = tskit.MetadataSchema({"codec":"json"})
>>> tc.metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benj/projects/tskit/python/tskit/tables.py", line 2146, in metadata
    return self.metadata_schema.decode_row(self._ll_tables.metadata)
  File "/home/benj/projects/tskit/python/tskit/metadata.py", line 117, in decode
    return json.loads(encoded.decode())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
You've set a schema, without setting the metadata, so the metadata is invalid.

**Comment by jeromekelleher** [comment]
So, the empty string isn't valid JSON... Not sure it's worth putting much effort in here, it's a pretty limited audience.

**Comment by hyanwong** [comment]
Oh, damn. Sorry. Didn't spot that.

**Comment by jeromekelleher** [comment]
Let's change the name to "better error messages for malformed metadata" and punt to "Python upcoming"

**Comment by benjeffery** [comment]
> Oh, damn. Sorry. Didn't spot that.

It's all good as metadata wasn't tested! https://github.com/tskit-dev/tskit/pull/997

**Comment by benjeffery** [comment]
Closing for inactivity and labelling "future", please re-open if you plan to work on this.
